version: '3.8'

services:
  triton:
    build: .
    container_name: triton
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - "$BASEDIR/triton-tutorial/model_repository:/models"
    shm_size: 256m
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
